#pragma config(Motor,  port2,           rearleftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontleftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rearrightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontrightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightencoderMotor, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           leftencoderMotor, tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]

task main()
{

  motor[rearrightMotor] = C1LY + C1LX + C1RX;
	motor[frontrightMotor] = C1LY - C1LX + C1RX;
	motor[rearleftMotor] = -C1LY + C1LX + C1RX;
	motor[frontleftMotor] = -C1LY - C1LX + C1RX;

/*motor[rearleftMotor] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
motor[frontleftMotor] = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
motor[rearrightMotor] = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
motor[frontleftMotor] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];

/*motor[leftencoderMotor]=77;  //moves left shooting motor
	motor[rightencoderMotor]=77;
	//motor[conveyerBelt]=-100;
	wait1Msec(23000);

	motor[leftencoderMotor]=0;
	motor[rightencoderMotor]=0;



    /*motor[frontleftMotor] = vexRT[Ch3];
		motor[frontrightMotor] = vexRT[Ch3];
		motor[rearleftMotor] = vexRT[Ch3];
		motor[rearrightMotor] = vexRT[Ch3];

/*	motor[leftencoderMotor]=77;  //moves left shooting motor
	motor[rightencoderMotor]=77;
	//motor[conveyerBelt]=-100;
	wait1Msec(23000);

	motor[leftencoderMotor]=0;
	motor[rightencoderMotor]=0;

			//Drive Straight
    motor[rearrightMotor] = 100;
		motor[frontrightMotor] = 100;
		motor[frontleftMotor] = 70;
		motor[rearleftMotor] = 70;
		/*motor[RCM]= 127;
  	motor[LCM]= 127;*/
	/*	wait1Msec(1200);
		motor[rearrightMotor] = 0;
		motor[frontrightMotor] = 0;
		motor[frontleftMotor] = 0;
		motor[rearleftMotor] = 0;


		/*motor[RCM]= 0;
  	motor[LCM]= 0;*/


	/*	motor[frontleftMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;  // (y + x)/2
		motor[frontrightMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;  // (y - x)/2
		motor[rearleftMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;  // (y + x)/2
		motor[rearrightMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;  // (y - x)/2*/


}
