#pragma config(Motor,  port2,           rearleftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontleftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rearrightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontrightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightencoderMotor, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           leftencoderMotor, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           conveyerBelt,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontintakeMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch1]
#define C1RX vexRT[Ch3]

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  motor[rearrightMotor] = C1LY + C1LX + C1RX;
	motor[frontrightMotor] = C1LY - C1LX + C1RX;
	motor[rearleftMotor] = -C1LY + C1LX + C1RX;
	motor[frontleftMotor] = -C1LY - C1LX + C1RX;

	if (vexRT[Btn5D] == 1)
	{
		motor[conveyerBelt] = -127;
 	}
  else if (vexRT[Btn5U] == 1)
  {
  	motor[conveyerBelt] = 115;
  }
 	else
 	{
  	motor[conveyerBelt] = 0;
 	}
 	if (vexRT[Btn6D] == 1)
	{
		motor[frontintakeMotor] = -127;
 	}
  else if (vexRT[Btn6U] == 1)
  {
  	motor[frontintakeMotor] = 115;
  }
 	else
 	{
  	motor[frontintakeMotor] = 0;
 	}
 	//Button control encoder:
		if(vexRT[Btn7U] == 1)
		{
			motor[leftencoderMotor] = 86;
			motor[rightencoderMotor] = 86;
		}

		if(vexRT[Btn7L] == 1)
		{
			motor[leftencoderMotor] = 60;
			motor[rightencoderMotor] = 60;
		}

		if(vexRT[Btn7R] == 1)
		{
			motor[leftencoderMotor] = 127;
			motor[rightencoderMotor] = 127;
		}

		else if (vexRT[Btn7D] == 1)
		{
			motor[leftencoderMotor] = 58;
			motor[rightencoderMotor] = 58;
		}

		else
		{
			motor[leftencoderMotor] = 0;
			motor[rightencoderMotor] = 0;
		}
  }
}
